name: Build flashcard-bootstrap

on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: build r4isdhc/dsbize patcher
        run: |
          sudo apt update
          sudo apt install -y gcc
          gcc -o resource/r4isdhc/r4isdhc resource/r4isdhc/r4isdhc.c
          gcc -o resource/dsbize/dsbize resource/dsbize/dsbize.c
          chmod +x resource/r4isdhc/r4isdhc
          chmod +x resource/dsbize/dsbize
      - name: Make flashcard-bootstrap
        run: |
          make dist
      - name: Prepare for build publishing
        run: |
          mkdir -p ~/artifacts
          cp bootstrap.zip ~/artifacts
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: build
